### ISSUE TITLE
why do you use Elastic Search

### ISSUE THREAD

**Issue by MaryLilian** [edgarmoarmask/SolrNet#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Elastic search in your project instead of others like Redis Search or Full text search extension for RDBMS , are there any special features that others dont have it. Can you share me it. I am wondering when I should choose KubeMQ instead of others like Redis Search or Full text search extension

**Comment by edgarmoarmask** [comment]
Hi,
First thing first, is your intention. Will you use it for structured or unstructured data. Redis is mostly used for caching in key value. RDBMS is for structured , while Solr is a nosql database. For example: one can upload pdf file through extractors and Tika library will extract the content.
